name: Publish Docker image

on:
  push:
    branches: [ main ]  # или ваша основная ветка
  # Можно добавить теги, если нужно:
  # tags: [ 'v*' ]

env:
#  DOCKER_IMAGE: ${{ secrets.DOCKER_USERNAME }}/it-support-portal-frontend  # ← замените my-app-name на желаемое имя образа
  REGISTRY: harbor.company.com
  IMAGE_NAME: it-support-portal/frontend

jobs:
  push_to_harbor:
    name: Push Docker image to Harbor
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha,prefix=sha-

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
